#include <cstdint>
#pragma once

namespace CPUID {
enum {
  // ecx
  CPUID_FEAT_SSE3 = 0,
  CPUID_FEAT_PCLMUL = 1,
  CPUID_FEAT_DTES64 = 2,
  CPUID_FEAT_MONITOR = 3,
  CPUID_FEAT_DS_CPL = 4,
  CPUID_FEAT_VMX = 5,
  CPUID_FEAT_SMX = 6,
  CPUID_FEAT_EST = 7,
  CPUID_FEAT_TM2 = 8,
  CPUID_FEAT_SSSE3 = 9,
  CPUID_FEAT_CID = 10,
  CPUID_FEAT_SDBG = 11,
  CPUID_FEAT_FMA = 12,
  CPUID_FEAT_CX16 = 13,
  CPUID_FEAT_XTPR = 14,
  CPUID_FEAT_PDCM = 15,
  CPUID_FEAT_PCID = 17,
  CPUID_FEAT_DCA = 18,
  CPUID_FEAT_SSE4_1 = 19,
  CPUID_FEAT_SSE4_2 = 20,
  CPUID_FEAT_X2APIC = 21,
  CPUID_FEAT_MOVBE = 22,
  CPUID_FEAT_POPCNT = 23,
  CPUID_FEAT_TSC = 24,
  CPUID_FEAT_AES = 25,
  CPUID_FEAT_XSAVE = 26,
  CPUID_FEAT_OSXSAVE = 27,
  CPUID_FEAT_AVX = 28,
  CPUID_FEAT_F16C = 29,
  CPUID_FEAT_RDRAND = 30,
  CPUID_FEAT_HYPERVISOR = 31,
  // edx
  CPUID_FEAT_FPU = 32,
  CPUID_FEAT_VME = 33,
  CPUID_FEAT_DE = 34,
  CPUID_FEAT_PSE = 35,
  CPUID_FEAT_EDX_TSC = 36, // BRUH
  CPUID_FEAT_MSR = 37,
  CPUID_FEAT_PAE = 38,
  CPUID_FEAT_MCE = 39,
  CPUID_FEAT_CX8 = 40,
  CPUID_FEAT_APIC = 41,
  CPUID_FEAT_SEP = 42,
  CPUID_FEAT_MTRR = 43,
  CPUID_FEAT_PGE = 44,
  CPUID_FEAT_MCA = 45,
  CPUID_FEAT_CMOV = 46,
  CPUID_FEAT_PAT = 47,
  CPUID_FEAT_PSE36 = 48,
  CPUID_FEAT_PSN = 49,
  CPUID_FEAT_CLFLUSH = 50,
  CPUID_FEAT_DS = 51,
  CPUID_FEAT_ACPI = 52,
  CPUID_FEAT_MMX = 53,
  CPUID_FEAT_FXSR = 54,
  CPUID_FEAT_SSE = 55,
  CPUID_FEAT_SSE2 = 56,
  CPUID_FEAT_SS = 57,
  CPUID_FEAT_HTT = 58,
  CPUID_FEAT_TM = 59,
  CPUID_FEAT_IA64 = 60,
  CPUID_FEAT_PBE = 61
};

const char *getVendorIDString();
bool checkCPUFeature(uint16_t feature);

} // namespace CPUID

extern "C" void callCPUID(uint32_t eax);